In [11]:
from pyscf import gto, scf, ao2mo
import pyscf.fci.selected_ci as sci
import pyscf.fci as fci
from pyscf.fci.direct_spin1 import _unpack_nelec
from pyscf.fci import cistring, SCI
import numpy as np
import ctypes
from functools import reduce
import math
import matplotlib.pyplot as plt

In [12]:
astrs = np.array([0b0011, 0b0101, 0b0110, 0b1001, 0b1010, 0b1100])
bstrs = np.array([0b0001, 0b0010, 0b0100, 0b1000])
ci_strs = (astrs, bstrs)
norb = 4
nelec = (2, 1)
cd_indexa, dd_indexa, cd_indexb, dd_indexb = sci._all_linkstr_index(ci_strs, norb, nelec)

In [13]:
print(cd_indexa.shape, dd_indexa.shape, cd_indexb.shape)

(6, 6, 4) (1, 16, 4) (4, 4, 4)


In [22]:
print(np.vectorize(np.binary_repr)(astrs, width=4))
print()
for (astr, index_entry) in zip(astrs, cd_indexa):
    print(bin(astr))
    print(index_entry)

['0011' '0101' '0110' '1001' '1010' '1100']

0b11
[[ 0  0  0  1]
 [ 2  0  0  1]
 [ 3  0  2 -1]
 [ 4  0  1  1]
 [ 6  0  4 -1]
 [ 7  0  3  1]]
0b101
[[ 0  0  1  1]
 [ 5  0  1  1]
 [ 1  0  2  1]
 [ 4  0  0  1]
 [ 6  0  5 -1]
 [ 8  0  3  1]]
0b110
[[ 2  0  2  1]
 [ 5  0  2  1]
 [ 1  0  1  1]
 [ 3  0  0 -1]
 [ 7  0  5 -1]
 [ 8  0  4  1]]
0b1001
[[0 0 3 1]
 [9 0 3 1]
 [1 0 4 1]
 [7 0 0 1]
 [3 0 5 1]
 [8 0 1 1]]
0b1010
[[ 2  0  4  1]
 [ 9  0  4  1]
 [ 1  0  3  1]
 [ 6  0  0 -1]
 [ 4  0  5  1]
 [ 8  0  2  1]]
0b1100
[[ 5  0  5  1]
 [ 9  0  5  1]
 [ 3  0  3  1]
 [ 6  0  1 -1]
 [ 4  0  4  1]
 [ 7  0  2 -1]]


In [23]:
print(dd_indexa)

[[[ 0  0  0 -1]
  [ 1  0  1 -1]
  [ 2  0  2 -1]
  [ 3  0  3 -1]
  [ 4  0  4 -1]
  [ 5  0  5 -1]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]
